= Hodei cli

== Introducción

Utilidad para ejecutar procesos de Hodei que se comunica con los microservicios de la plataforma a
través de RabbitMQ.

== Comandos

|===
|`read-customer`          |Recupera el JSON de una determinada persona de MongoDB a partir del identificador.
|`pull-countries`         |Envía un mensaje de sincronización de países.
|`pull-products`          |Envía un mensaje de sincronización de productos.
|`pull-agreements`        |Envía un mensaje de sincronización de acuerdos marco.
|`pull-networks`          |Envía un mensaje de sincronización de comercializadoras.
|`pull-customers`         |Envía un mensaje de sincronización de personas físicas y jurídicas.
|`pull-professions`       |Envía un mensaje de sincronización de profesiones.
|`pull-policies`          |Envía un mensaje de sincronización de pólizas.
|`mongo-reset`            |Reestablece la base de datos a su configuración inicial.
|`signature-request`      |Envía un mensaje de solicitud de firma de un documento.
|`check-iban`             |Envía un mensaje para la validación de un determinado IBAN.
|===

Para consultar las opciones de cada operativa basta con pasar el argumento `-help` al comando que deseamos ejecutar.

== Configuración

Eta utilidad requiere de la variable de sistema `APP_AMQP_URI` para establecer la conexión con
Rabbit. El formato esperado es el siguiente:

----
APP_AMQP_URI=guest:guest@localhost:5672/
----


== Ejemplos

----
hodei-cli pull-networks -idcard 70111222A -u demo -a -demo

hodei-cli pull-policies -product ppi -agreement 20725 -u demo -a demo
----

== Instalación

----
go get github.com/streadway/amqp

dep ensure -add "go.mongodb.org/mongo-driver/mongo@~1.0.0"

./gradlew goClean goBuild
----

La construcción generá el binario dependiente de la plataforma en la carpeta _%{GOPATH}/bin_ que 
podremos ejecutar:

----
hodei-cli version
----