= Hodei cli

== Introducción

Utilidad para ejecutar procesos de Hodei que se comunica con los microservicios de la plataforma a
través de RabbitMQ.

== Comandos

|===
|`read-person`            |Recupera el JSON de una determinada persona de MongoDB a partir del identificador.
|`pull-countries`         |Envía un mensaje de sincronización de países.
|`pull-products`          |Envía un mensaje de sincronización de productos y acuerdos marco.
|`pull-policies`          |Envía un mensaje de sincronización de pólizas.
|`check-iban`             |Envía un mensaje para la validación de un determinado IBAN.
|===

Para consultar las opciones de cada operativa basta con pasar el argumento `-help` al comando que deseamos ejecutar.

== Configuración

Eta utilidad requiere de la variable de sistema `APP_AMQP_URI` para establecer la conexión con
Rabbit. El formato esperado es el siguiente:

----
APP_AMQP_URI=guest:guest@localhost:5672/
----


== Instalación

----
go get github.com/streadway/amqp
./gradlew goClean goBuild
----

La construcción generá el binario dependiente de la plataforma en la carpeta _%{GOPATH}/bin_ que 
podremos ejecutar:

----
hodei-cli version
----